name: flat
on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./peraturan.go.id/postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.33.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://peraturan.go.id/sitemap.xml
          downloaded_filename: peraturan.go.id/sitemap.xml
          postprocess: ./peraturan.go.id/postprocess.ts
