name: peraturan.go.id
on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/peraturan.go.id.yml
      - ./peraturan.go.id/postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://peraturan.go.id/sitemap.xml
          downloaded_filename: peraturan.go.id/sitemap.xml
      - name: Process file
        run: deno run -A ./peraturan.go.id/postprocess.ts ./peraturan.go.id/sitemap.xml
      - id: git-check
        name: Check for modified files
        run: echo SELECTED_COLOR=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi) >> "$GITHUB_OUTPUT"
      - name: Commit & Push
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push