name: peraturan.go.id
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: 
    inputs:
      start:
        type: boolean
  push:
    paths:
      - .github/workflows/peraturan.go.id.yml
      - ./peraturan.go.id/postprocess.ts
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cache Deno dependencies 
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/deno
          key: ${{ hashFiles('deno.lock') }}
      - name: Cache _temp_ folder
        uses: actions/cache@v3
        with:
          path: ./peraturan.go.id/_temp_
          key: temp-${{runner.name}}-${{ github.run_id }}
          restore-keys: temp-${{runner.name}}
      - name: Run script
        working-directory: ./peraturan.go.id/
        run: deno run -A --unstable main.ts ${{ github.event.inputs.start == 'true' && '--start' }}
      - id: git-check
        name: Check for modified files
        run: echo modified=$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi) >> "$GITHUB_OUTPUT"
      - name: Commit & Push
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push